window:
  decorations: none
  startup_mode: Fullscreen
  gtk_theme_variant: dark
font:
  normal:
    family: FiraCode Nerd Font
  italic:
    family: FiraCode Nerd Font
  bold:
    family: FiraCode Nerd Font
